// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU43aEO53i-5uN-wLjHh7DIe3I0Zllhvs',
    appId: '1:763555864410:web:32d931af931783ac899d63',
    messagingSenderId: '763555864410',
    projectId: 'crossword-8e698',
    authDomain: 'crossword-8e698.firebaseapp.com',
    storageBucket: 'crossword-8e698.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFu2BbqA4sCys_2C10cGAfrSsnqr0OFgk',
    appId: '1:763555864410:android:6cb77f108f582e5a899d63',
    messagingSenderId: '763555864410',
    projectId: 'crossword-8e698',
    storageBucket: 'crossword-8e698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQZkMbsESs_IxDAemC-_xAOJZgtFY4gpo',
    appId: '1:763555864410:ios:d08ebe9ba7873d7e899d63',
    messagingSenderId: '763555864410',
    projectId: 'crossword-8e698',
    storageBucket: 'crossword-8e698.appspot.com',
    iosClientId: '763555864410-o0kfgsn3akckg76v7eq3ctmepc68bqi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.crossword',
  );
}
